services:
  zentry-db:
    image: postgres:16
    container_name: zentry_postgres
    environment:
      - POSTGRES_DB=zentry_iam
      - POSTGRES_USER=ranxom
      - POSTGRES_PASSWORD=super_secure_password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ranxom -d zentry_iam"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - zentry-net

  zentry-redis:
    image: redis:7-alpine
    container_name: zentry_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - zentry-net

  zentry-app:
    image: ranxom/zentry:latest
    container_name: zentry_sentinel
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://zentry-db:5432/zentry_iam
      - SPRING_DATASOURCE_USERNAME=ranxom
      - SPRING_DATASOURCE_PASSWORD=super_secure_password
      - SPRING_DATA_REDIS_HOST=zentry-redis
      - SPRING_DATA_REDIS_PORT=6379
      - ZENTRY_SECURITY_JWT_SECRET=VfeLjnKDK8d77nM35aHtlgV3G8XVg3fcps0PgR9pnzA
    depends_on:
      zentry-db:
        condition: service_healthy
      zentry-redis:
        condition: service_healthy
    networks:
      - zentry-net

networks:
  zentry-net:
    driver: bridge