spring.datasource.url=jdbc:postgresql://localhost:5432/zentry_iam
spring.datasource.username=ranxom
spring.datasource.password=super_secure_password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

zentry.security.jwt.secret=${LOCAL_JWT_SECRET}
zentry.security.jwt.expiration=3600000