spring.datasource.url=jdbc:postgresql://localhost:5432/zentry_iam
spring.datasource.username=ranxom
spring.datasource.password=super_secure_password
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

zentry.security.jwt.secret=VfeLjnKDK8d77nM35aHtlgV3G8XVg3fcps0PgR9pnzA=
zentry.security.jwt.expiration=3600000

zentry.security.jwt.refresh-expiration=604800000