# --- Database Connection ---
spring.datasource.url=jdbc:h2:mem:zentry_test;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Disable Hibernate's auto-gen so it doesn't fight with Flyway
spring.jpa.hibernate.ddl-auto=none
# Ensure Flyway is active for the test environment
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always